# Generated by Django 5.1.3 on 2024-12-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate_api', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchmate_api.streamplatform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
